### ISSUE TITLE
Custom antora.yml asciidoc attributes are ignored by pdf generation

### ISSUE THREAD

**Issue by ludwigmair** [asciidoctor/asciidoctor.js#1271]
Hi,

my question is if custom page attributes coming from antora.yml  are supported in case documentation gets generated as pdf using asciidoctor. 

My idea was to place page-wide used attributes in the antora.yml file to access them easily everywhere in documentation.
unfortunately, it does not work.

even so, I have trouble to set page attributes e.g. like `page-component-title` and get them replaced in a generated pdf

Perhaps my thinking is wrong, but logic wise it would be great to do so?

we do have documentation for various software modules in different versions. for each model exists a new branch with a different version. some values/text... appear on different locations in a documentation with version dependent infos etc. for this case I was thinking this would be solution, but it is not working. 

antora.yml:
```
name: "my-modulname"
title: "My Title"
version: "1.0"
start_page: ROOT:index.adoc
nav:
  - modules/ROOT/nav.adoc
 asciidoc:
  attributes:
     my-custom-atribute: "Lorem Ipsum"
```

output in pdf:
```
{my-custom-atribute}
```
thanks a lot for any help

best regards Ludwig
