### ISSUE TITLE
Target directory does not exist

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor.js#204]
This error is reported even if the directory exists.

```
IOError: target directory does not exist: /Users/chmoulli/Google-Drive/REDHAT/RH-GP/Reports/2016/generated_content
    at SingletonClass_alloc.$new (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:4512:15)
    at SingletonClass_alloc.$exception (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:4530:31)
    at module_constructor.<anonymous> (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/node_modules/opal-npm-wrapper/index.js:4281:31)
    at module_constructor.<anonymous> (/Users/chmoulli/.nvm/versions/node/v4.2.0/lib/node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js:647:385)
```

The error is reported by this line of code within asciidoctor-core.js

```
 } else if (to_file !== false && to_file !== nil) {
  outfile = doc.$normalize_system_path(to_file, working_dir, jail, $hash2(["target_name", "recover"], {"target_name": "to_dir", "recover": false}));
  outdir = Opal.get('File').$dirname(outfile);}; ////// HERE //////
```

![screenshot 2016-08-18 17 22 20](https://cloud.githubusercontent.com/assets/463790/17779578/6af9c46c-6568-11e6-8048-53cd395b23c8.png)
![screenshot 2016-08-18 17 22 29](https://cloud.githubusercontent.com/assets/463790/17779577/6af99668-6568-11e6-9d83-6e089f3ced2b.png)

Code

```
function convertToHtml(content) {

    var attrs = opal.hash(cfg.attributes);
    var options = opal.hash(cfg.options);
    options["$[]="]("attributes",attrs);

    try {
        var html = processor.$convert(content, options);
        fs.writeFileSync("./generated_content/output.html", html);
    } catch (e) {
        console.error(e.stack);
    }
}
```

Config

```
file_to_process: "./minutes/test.adoc"

attributes:
  showtitle: ''
  stylesheet: 'foundation.css'
  stylesdir: 'css'
  nofooter: 'yes'
  linkcss: 'true'

options:
  doctype: 'article'
  header_footer: 'false'
  to_dir: './generated_content'
  to_file: 'output.html'
  safe: 'unsafe' # Required to avoid that the file to process is not loaded
```
